<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Init</code>
 */
class Init extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Statistic init_stat = 1;</code>
     */
    private $init_stat = null;
    /**
     * Generated from protobuf field <code>sint32 account_id = 2;</code>
     */
    private $account_id = 0;
    /**
     * Generated from protobuf field <code>string api_key = 3;</code>
     */
    private $api_key = '';
    /**
     * Generated from protobuf field <code>sint32 rule_id = 4;</code>
     */
    private $rule_id = 0;
    /**
     * Generated from protobuf field <code>string reference_ip = 5;</code>
     */
    private $reference_ip = '';
    /**
     * Generated from protobuf field <code>sint32 queue_id = 6;</code>
     */
    private $queue_id = 0;
    /**
     * optional. use to continue processing after disconnect
     *
     * Generated from protobuf field <code>string session_id = 10;</code>
     */
    private $session_id = '';
    /**
     * default: 0.02
     *
     * Generated from protobuf field <code>double maximum_error_rate = 12;</code>
     */
    private $maximum_error_rate = 0.0;
    /**
     * Generated from protobuf field <code>sint32 version = 13;</code>
     */
    private $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Statistic $init_stat
     *     @type int $account_id
     *     @type string $api_key
     *     @type int $rule_id
     *     @type string $reference_ip
     *     @type int $queue_id
     *     @type string $session_id
     *           optional. use to continue processing after disconnect
     *     @type float $maximum_error_rate
     *           default: 0.02
     *     @type int $version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Statistic init_stat = 1;</code>
     * @return \Statistic
     */
    public function getInitStat()
    {
        return $this->init_stat;
    }

    /**
     * Generated from protobuf field <code>.Statistic init_stat = 1;</code>
     * @param \Statistic $var
     * @return $this
     */
    public function setInitStat($var)
    {
        GPBUtil::checkMessage($var, \Statistic::class);
        $this->init_stat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 account_id = 2;</code>
     * @return int
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Generated from protobuf field <code>sint32 account_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkInt32($var);
        $this->account_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string api_key = 3;</code>
     * @return string
     */
    public function getApiKey()
    {
        return $this->api_key;
    }

    /**
     * Generated from protobuf field <code>string api_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setApiKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 rule_id = 4;</code>
     * @return int
     */
    public function getRuleId()
    {
        return $this->rule_id;
    }

    /**
     * Generated from protobuf field <code>sint32 rule_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRuleId($var)
    {
        GPBUtil::checkInt32($var);
        $this->rule_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reference_ip = 5;</code>
     * @return string
     */
    public function getReferenceIp()
    {
        return $this->reference_ip;
    }

    /**
     * Generated from protobuf field <code>string reference_ip = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setReferenceIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->reference_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 queue_id = 6;</code>
     * @return int
     */
    public function getQueueId()
    {
        return $this->queue_id;
    }

    /**
     * Generated from protobuf field <code>sint32 queue_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setQueueId($var)
    {
        GPBUtil::checkInt32($var);
        $this->queue_id = $var;

        return $this;
    }

    /**
     * optional. use to continue processing after disconnect
     *
     * Generated from protobuf field <code>string session_id = 10;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * optional. use to continue processing after disconnect
     *
     * Generated from protobuf field <code>string session_id = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * default: 0.02
     *
     * Generated from protobuf field <code>double maximum_error_rate = 12;</code>
     * @return float
     */
    public function getMaximumErrorRate()
    {
        return $this->maximum_error_rate;
    }

    /**
     * default: 0.02
     *
     * Generated from protobuf field <code>double maximum_error_rate = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setMaximumErrorRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->maximum_error_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 version = 13;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>sint32 version = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

}

