<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PutTask</code>
 */
class PutTask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes customData = 1;</code>
     */
    private $customData = '';
    /**
     * Generated from protobuf field <code>string taskUUID = 2;</code>
     */
    private $taskUUID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customData
     *     @type string $taskUUID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes customData = 1;</code>
     * @return string
     */
    public function getCustomData()
    {
        return $this->customData;
    }

    /**
     * Generated from protobuf field <code>bytes customData = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomData($var)
    {
        GPBUtil::checkString($var, False);
        $this->customData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string taskUUID = 2;</code>
     * @return string
     */
    public function getTaskUUID()
    {
        return $this->taskUUID;
    }

    /**
     * Generated from protobuf field <code>string taskUUID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskUUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->taskUUID = $var;

        return $this;
    }

}

