<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

if (false) {
    /**
     * This class is deprecated. Use RequestMessage\Type instead.
     * @deprecated
     */
    class RequestMessage_Type {}
}
class_exists(RequestMessage\Type::class);
@trigger_error('RequestMessage_Type is deprecated and will be removed in the next major release. Use RequestMessage\Type instead', E_USER_DEPRECATED);

