<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RequestMessage</code>
 */
class RequestMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.RequestMessage.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.PutTask task = 2;</code>
     */
    private $task = null;
    /**
     * Generated from protobuf field <code>.Init init = 3;</code>
     */
    private $init = null;
    /**
     * Generated from protobuf field <code>.Statistic statistic = 4;</code>
     */
    private $statistic = null;
    /**
     * Generated from protobuf field <code>.ErrRate errRate = 5;</code>
     */
    private $errRate = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \PutTask $task
     *     @type \Init $init
     *     @type \Statistic $statistic
     *     @type \ErrRate $errRate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.RequestMessage.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.RequestMessage.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \RequestMessage_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PutTask task = 2;</code>
     * @return \PutTask
     */
    public function getTask()
    {
        return $this->task;
    }

    /**
     * Generated from protobuf field <code>.PutTask task = 2;</code>
     * @param \PutTask $var
     * @return $this
     */
    public function setTask($var)
    {
        GPBUtil::checkMessage($var, \PutTask::class);
        $this->task = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Init init = 3;</code>
     * @return \Init
     */
    public function getInit()
    {
        return $this->init;
    }

    /**
     * Generated from protobuf field <code>.Init init = 3;</code>
     * @param \Init $var
     * @return $this
     */
    public function setInit($var)
    {
        GPBUtil::checkMessage($var, \Init::class);
        $this->init = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Statistic statistic = 4;</code>
     * @return \Statistic
     */
    public function getStatistic()
    {
        return $this->statistic;
    }

    /**
     * Generated from protobuf field <code>.Statistic statistic = 4;</code>
     * @param \Statistic $var
     * @return $this
     */
    public function setStatistic($var)
    {
        GPBUtil::checkMessage($var, \Statistic::class);
        $this->statistic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ErrRate errRate = 5;</code>
     * @return \ErrRate
     */
    public function getErrRate()
    {
        return $this->errRate;
    }

    /**
     * Generated from protobuf field <code>.ErrRate errRate = 5;</code>
     * @param \ErrRate $var
     * @return $this
     */
    public function setErrRate($var)
    {
        GPBUtil::checkMessage($var, \ErrRate::class);
        $this->errRate = $var;

        return $this;
    }

}

