<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ServiceMessage</code>
 */
class ServiceMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ServiceMessage.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.GetTask request = 2;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>.InitResponse init = 3;</code>
     */
    private $init = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \GetTask $request
     *     @type \InitResponse $init
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ServiceMessage.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.ServiceMessage.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \ServiceMessage_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GetTask request = 2;</code>
     * @return \GetTask
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.GetTask request = 2;</code>
     * @param \GetTask $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \GetTask::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.InitResponse init = 3;</code>
     * @return \InitResponse
     */
    public function getInit()
    {
        return $this->init;
    }

    /**
     * Generated from protobuf field <code>.InitResponse init = 3;</code>
     * @param \InitResponse $var
     * @return $this
     */
    public function setInit($var)
    {
        GPBUtil::checkMessage($var, \InitResponse::class);
        $this->init = $var;

        return $this;
    }

}

