<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

if (false) {
    /**
     * This class is deprecated. Use ServiceMessage\Type instead.
     * @deprecated
     */
    class ServiceMessage_Type {}
}
class_exists(ServiceMessage\Type::class);
@trigger_error('ServiceMessage_Type is deprecated and will be removed in the next major release. Use ServiceMessage\Type instead', E_USER_DEPRECATED);

