<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Statistic</code>
 */
class Statistic extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double avgTimeTalkSec = 1;</code>
     */
    private $avgTimeTalkSec = 0.0;
    /**
     * Generated from protobuf field <code>double percentSuccessful = 2;</code>
     */
    private $percentSuccessful = 0.0;
    /**
     * Generated from protobuf field <code>double avgDialTimeSec = 3;</code>
     */
    private $avgDialTimeSec = 0.0;
    /**
     * Generated from protobuf field <code>double avgTotalTimeSec = 4;</code>
     */
    private $avgTotalTimeSec = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $avgTimeTalkSec
     *     @type float $percentSuccessful
     *     @type float $avgDialTimeSec
     *     @type float $avgTotalTimeSec
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double avgTimeTalkSec = 1;</code>
     * @return float
     */
    public function getAvgTimeTalkSec()
    {
        return $this->avgTimeTalkSec;
    }

    /**
     * Generated from protobuf field <code>double avgTimeTalkSec = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgTimeTalkSec($var)
    {
        GPBUtil::checkDouble($var);
        $this->avgTimeTalkSec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double percentSuccessful = 2;</code>
     * @return float
     */
    public function getPercentSuccessful()
    {
        return $this->percentSuccessful;
    }

    /**
     * Generated from protobuf field <code>double percentSuccessful = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setPercentSuccessful($var)
    {
        GPBUtil::checkDouble($var);
        $this->percentSuccessful = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avgDialTimeSec = 3;</code>
     * @return float
     */
    public function getAvgDialTimeSec()
    {
        return $this->avgDialTimeSec;
    }

    /**
     * Generated from protobuf field <code>double avgDialTimeSec = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgDialTimeSec($var)
    {
        GPBUtil::checkDouble($var);
        $this->avgDialTimeSec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avgTotalTimeSec = 4;</code>
     * @return float
     */
    public function getAvgTotalTimeSec()
    {
        return $this->avgTotalTimeSec;
    }

    /**
     * Generated from protobuf field <code>double avgTotalTimeSec = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgTotalTimeSec($var)
    {
        GPBUtil::checkDouble($var);
        $this->avgTotalTimeSec = $var;

        return $this;
    }

}

